### ISSUE TITLE
Randomize target location

### ISSUE THREAD

**Issue by alternadiva** [alternadiva/Snake-Game#3]

**Comment by mariaalouisaa** [comment]
Review :)

- Really cool to see that even though we've both used canvas there are a lot of differences already!
- Even though you said your variable names weren't so related your code is still clear to follow and very tidy.

- This is cool, I haven't seen key codes picked up like this. ⬇️
https://github.com/alternadiva/Snake-Game/blob/cd812e8b5297039dea446218e9200f79b0543149/script.js#L72

- I think the reason why the food is not lining up with the snake is that the "random spot" the food appears on the board needs to be a multiple of whatever width the snake head is.... then they _should_ line up nicely ⬇️
https://github.com/alternadiva/Snake-Game/blob/cd812e8b5297039dea446218e9200f79b0543149/script.js#L86-L89 

It's looking great so far 🎉

**Comment by alternadiva** [comment]
> * I think the reason why the food is not lining up with the snake is that the "random spot" the food appears on the board needs to be a multiple of whatever width the snake head is.... then they _should_ line up nicely ⬇️
>   https://github.com/alternadiva/Snake-Game/blob/cd812e8b5297039dea446218e9200f79b0543149/script.js#L86-L89
> 

Thank you for the amazing suggestion, Maria! Solved the issue perfectly ✨
